[build]
  publish = "_site"
  command = "npm run build"

[[redirects]]
  from = "/sitemap.txt"
  to = "/sitemap.xml"
  status = 301

[[redirects]]
  from = "/clapsed-pattern-scarf/"
  to = "/clasped-pattern-scarf/"
  status = 301